version: '3'
services:

    shard_master:
        image: postgres:11
        env_file:
            - ./postgres.env
        container_name: "shard_master"
        restart: "no"
        ports:
            - "5432:5432"
        volumes:
            - ./shard_master.sql:/docker-entrypoint-initdb.d/shard_master.sql
            - ./dump.sql:/dump.sql
            - ./dumpNoShard.sql:/dumpNoShard.sql
            - ./loadShard.sh:/loadShard.sh
            - ./loadNoShard.sh:/loadNoShard.sh
        networks:
            - shard

    shard_1:
        image: postgres:11
        env_file:
            - ./postgres.env
        container_name: "shard_1"
        restart: "no"
        depends_on:
            - shard_master
        volumes:
            - ./shard_1.sql:/docker-entrypoint-initdb.d/shard_1.sql
        networks:
            - shard

    shard_2:
        image: postgres:11
        env_file:
            - ./postgres.env
        container_name: "shard_2"
        restart: "no"
        depends_on:
            - shard_master
        volumes:
            - ./shard_2.sql:/docker-entrypoint-initdb.d/shard_2.sql
        networks:
            - shard

networks:
    shard:

